"""empty message

Revision ID: 54d47f138276
Revises: 3b9138ee25f5
Create Date: 2020-11-18 16:59:50.135891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d47f138276'
down_revision = '3b9138ee25f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('image_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_link')
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###
