"""empty message

Revision ID: ab323d8a46f7
Revises: 4fd5259c251f
Create Date: 2020-11-13 12:47:16.210400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab323d8a46f7'
down_revision = '4fd5259c251f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('is_seeking_performance', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('is_seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'is_seeking_talent')
    op.drop_column('artists', 'is_seeking_performance')
    # ### end Alembic commands ###
