"""empty message

Revision ID: b66889cd79f3
Revises: 67978e16379f
Create Date: 2020-11-18 15:40:21.825107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66889cd79f3'
down_revision = '67978e16379f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('venues', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website')
    op.drop_table('shows')
    # ### end Alembic commands ###
